// This file is auto-generated by built-assets.js, do not edit!
const base = require('Flash').getFree()[0].addr + 4096;

module.exports = {
  0: E.memoryArea(base+0, 228), // 48x38
  1: E.memoryArea(base+228, 228), // 48x38
  2: E.memoryArea(base+456, 228), // 48x38
  3: E.memoryArea(base+684, 228), // 48x38
  4: E.memoryArea(base+912, 228), // 48x38
  5: E.memoryArea(base+1140, 228), // 48x38
  6: E.memoryArea(base+1368, 228), // 48x38
  7: E.memoryArea(base+1596, 228), // 48x38
  8: E.memoryArea(base+1824, 228), // 48x38
  9: E.memoryArea(base+2052, 228), // 48x38
  A: E.memoryArea(base+2280, 63), // 24x21
  colon: E.memoryArea(base+2344, 66), // 48x11
  E: E.memoryArea(base+2412, 63), // 24x21
  G: E.memoryArea(base+2476, 63), // 24x21
  H: E.memoryArea(base+2540, 63), // 24x21
  I: E.memoryArea(base+2604, 63), // 24x21
  M: E.memoryArea(base+2668, 63), // 24x21
  O: E.memoryArea(base+2732, 63), // 24x21
  R: E.memoryArea(base+2796, 63), // 24x21
  trex: E.memoryArea(base+2860, 175), // 40x35
  V: E.memoryArea(base+3036, 63), // 24x21
  s0: E.memoryArea(base+3100, 57), // 24x19
  s1: E.memoryArea(base+3160, 57), // 24x19
  s2: E.memoryArea(base+3220, 57), // 24x19
  s3: E.memoryArea(base+3280, 57), // 24x19
  s4: E.memoryArea(base+3340, 57), // 24x19
  s5: E.memoryArea(base+3400, 57), // 24x19
  s6: E.memoryArea(base+3460, 57), // 24x19
  s7: E.memoryArea(base+3520, 57), // 24x19
  s8: E.memoryArea(base+3580, 57), // 24x19
  s9: E.memoryArea(base+3640, 57), // 24x19
}
