// This file is auto-generated by built-assets.js, do not edit!
const base = 389120;

module.exports = {
  0: E.memoryArea(base+0, 228), // 48x38
  1: E.memoryArea(base+228, 228), // 48x38
  2: E.memoryArea(base+456, 228), // 48x38
  3: E.memoryArea(base+684, 228), // 48x38
  4: E.memoryArea(base+912, 228), // 48x38
  5: E.memoryArea(base+1140, 228), // 48x38
  6: E.memoryArea(base+1368, 228), // 48x38
  7: E.memoryArea(base+1596, 228), // 48x38
  8: E.memoryArea(base+1824, 228), // 48x38
  9: E.memoryArea(base+2052, 228), // 48x38
  A: E.memoryArea(base+2280, 63), // 24x21
  E: E.memoryArea(base+2344, 63), // 24x21
  G: E.memoryArea(base+2408, 63), // 24x21
  H: E.memoryArea(base+2472, 63), // 24x21
  I: E.memoryArea(base+2536, 63), // 24x21
  M: E.memoryArea(base+2600, 63), // 24x21
  O: E.memoryArea(base+2664, 63), // 24x21
  R: E.memoryArea(base+2728, 63), // 24x21
  trex: E.memoryArea(base+2792, 175), // 40x35
  V: E.memoryArea(base+2968, 63), // 24x21
}
