const fs = require('fs');
const path = require('path');
const bitmap = require('./util/bitmap');

function pad(bitmap) {
  while (bitmap.length % 4) {
    bitmap = [].concat(bitmap, [0]);
  }
  return bitmap;
}

let outputFile = fs.openSync(path.resolve('dist', 'bitmaps.js'), 'w');
fs.writeSync(outputFile, `
  // This file is auto-generated by built-assets.js, do not edit!

  let flash = require('Flash');
  let addr = flash.getFree()[0].addr;
  const pageSize = flash.getPage(addr).length;
  addr += pageSize;
  flash.erasePage(addr);
`.trim().replace(/\n  /g, '\n') + '\n');

let assetsOutputFile = fs.openSync('src/assets.js', 'w');
fs.writeSync(assetsOutputFile, `
  // This file is auto-generated by built-assets.js, do not edit!
  const base = require('Flash').getFree()[0].addr + 4096;

  module.exports = {    
`.trim().replace(/\n  /g, '\n') + '\n')

let flashOffset = 0;

function buildAsset(filePath, assetName) {
  const bitmapData = fs.readFileSync(filePath).toString();
  const image = bitmap.toBitmap(bitmapData);
  const paddedBitmap = pad(image.bitmap);
  const encoded = bitmap.encode(paddedBitmap);
  fs.writeSync(outputFile,
    `flash.write(atob('${encoded}'), addr+${flashOffset});\n`);
  fs.writeSync(assetsOutputFile,
    `  ${assetName}: E.memoryArea(base+${flashOffset}, ${image.bitmap.length}), // ${image.width}x${image.height}\n`);
  flashOffset += paddedBitmap.length;
}

for (let fileName of fs.readdirSync('assets')) {
  if (path.extname(fileName).toLowerCase() === '.txt') {
    buildAsset('assets/' + fileName, path.parse(fileName).name);
  }
}

for (let fileName of fs.readdirSync('assets/small')) {
  if (path.extname(fileName).toLowerCase() === '.txt') {
    buildAsset('assets/small/' + fileName, 's' + path.parse(fileName).name);
  }
}

fs.writeSync(outputFile, `// end offset: ${flashOffset}\n`);
fs.writeSync(assetsOutputFile, `}\n`);
